  name: build-spring-app-push-docker
  on:
    push:
      branches:
        - master

  jobs:
    build-deploy:
      name: build-spring-app-push-docker
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: setup jdk 17
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: 17

        - name: build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml
        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/rest-api:latest

        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/rest-api:latest
